# PROGRAM: Assignment 2
# AUTHOR: Luke Lemanski
# LOGON ID: Z1885842
# DUE DATE: February 21
assignment2.exe: assignment2.cpp
	g++ -Wall -Werror -o assignment2.exe assignment2.cpp
clean:
	rm -f *.o assignment2
